# Generated by Django 2.0.5 on 2019-02-01 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='git',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='homepage',
        ),
    ]
