export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION'
export const GET_ARTICLE_INFORMATION = 'GET_ARTICLE_INFORMATION'
export const GET_USER_LIST = 'GET_USER_LIST'



